update publish script

diff --git a/packages/plugin-flex/bin/publish b/packages/plugin-flex/bin/publish
--- a/packages/plugin-flex/bin/publish
+++ b/packages/plugin-flex/bin/publish
@@ -7,6 +7,7 @@
 ##    ./bin/publish patch/minor/major             publishes as beta
 
 DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
+CURRENT_BRANCH=$(git branch --show-current)
 
 # Release tag
 tag="alpha"
@@ -14,7 +15,7 @@ if [ "$1" == "public" ] ; then
   tag="public"
 fi
 if [ "$1" == "beta" ] ; then
-  tag="next"
+  tag="beta"
 fi
 # Version bump
 bump="patch"
@@ -26,6 +27,20 @@ if [ "$2" == "major" ] ; then
 fi
 if [ "$1" != "public" ] ; then
   bump="pre${bump}"
+fi
+
+# Verify tag and branch
+if [ "$CURRENT_BRANCH" == "main" ] && [ "$tag" != "public" ] ; then
+  echo "main branch can only have public release"
+  exit 1
+fi
+if [ "$tag" == "public" ] && [ "$CURRENT_BRANCH" != "main" ] ; then
+  echo "Public release must be done on the main branch"
+  exit 1
+fi
+if [ "$tag" == "alpha" ] && [[ "$CURRENT_BRANCH" =~ ^v.-beta$ ]] ; then
+  echo "Alpha release cannot be on a v*-beta branch"
+  exit 1
 fi
 
 # Version
