add versbose flag

diff --git a/.github/workflows/~reusable_e2e_by_OS.yaml b/.github/workflows/~reusable_e2e_by_OS.yaml
--- a/.github/workflows/~reusable_e2e_by_OS.yaml
+++ b/.github/workflows/~reusable_e2e_by_OS.yaml
@@ -102,7 +102,7 @@ jobs:
         run: |
           echo "Starting npm ci with a 10-minute timeout"
           for i in 1 2 3; do # Retry logic, retry 3 times
-            timeout 10m npm ci && break || echo "npm ci failed, retrying ($i/3)..."
+            timeout 10m npm ci --verbose && break || echo "npm ci failed, retrying ($i/3)..."
           done
       - name: Install project dependencies (Macos)
         if: ${{ inputs.OS == 'macos-latest' }}
@@ -111,7 +111,7 @@ jobs:
           echo "Starting npm ci with a 10-minute timeout"
           brew install coreutils
           for i in 1 2 3; do # Retry logic, retry 3 times
-            gtimeout 10m npm ci && break || echo "npm ci failed, retrying ($i/3)..."
+            gtimeout 10m npm ci --verbose && break || echo "npm ci failed, retrying ($i/3)..."
           done
       - name: Install project dependencies (Windows)
         if: ${{ inputs.OS == 'windows-latest' }}
@@ -120,7 +120,7 @@ jobs:
             $attempts = 3
             for ($i=1; $i -le $attempts; $i++) {
               try {
-                $process = Start-Process -FilePath 'npm' -ArgumentList 'ci' -NoNewWindow -PassThru
+                $process = Start-Process -FilePath 'npm' -ArgumentList 'ci --verbose' -NoNewWindow -PassThru
                 if ($process.WaitForExit(600000)) { # 10 minutes in milliseconds
                   echo 'npm ci completed successfully'
                   exit 0
