test macos

diff --git a/.github/workflows/~reusable_e2e.yaml b/.github/workflows/~reusable_e2e.yaml
--- a/.github/workflows/~reusable_e2e.yaml
+++ b/.github/workflows/~reusable_e2e.yaml
@@ -108,9 +108,10 @@ jobs:
           node-version: '20'
       - name: Install project dependencies
         run: |
-          echo "Starting npm ci with a 10-minute timeout"
+          echo "Starting npm ci with a 20-minute timeout"
+          brew install coreutils
           for i in 1 2 3; do # Retry logic, retry 3 times
-            timeout 20m npm ci && break || echo "npm ci failed, retrying ($i/3)..."
+            gtimeout 20m npm ci && break || echo "npm ci failed, retrying ($i/3)..."
           done
         shell: bash
       - name: Build packages
