test macos

diff --git a/.github/workflows/~reusable_e2e.yaml b/.github/workflows/~reusable_e2e.yaml
--- a/.github/workflows/~reusable_e2e.yaml
+++ b/.github/workflows/~reusable_e2e.yaml
@@ -69,39 +69,39 @@ env:
   NODE_OPTIONS: --max-old-space-size=8192
 
 jobs:
-  node20-ubuntu:
-    runs-on: ubuntu-latest
-    steps:
-      - uses: actions/checkout@v4
-      - uses: actions/setup-node@v3
-        with:
-          node-version: '20'
-      - name: Install project dependencies
-        run: |
-          echo "Starting npm ci with a 10-minute timeout"
-          for i in 1 2 3; do # Retry logic, retry 3 times
-            timeout 10m npm ci && break || echo "npm ci failed, retrying ($i/3)..."
-          done
-      - name: Build packages
-        run: npm run build
-      - name: Run e2e tests - JS
-        run: |
-          cd packages/flex-plugin-e2e-tests
-          npm run start
-        env:
-          TS: 0
-      - name: Run e2e tests - TS
-        env:
-          TS: 1
-        run: |
-          cd packages/flex-plugin-e2e-tests
-          npm run start
-      - name: Upload Screenshots
-        uses: actions/upload-artifact@v3
-        if: always()
-        with:
-          name: Ubuntu-screenshots
-          path: packages/flex-plugin-e2e-tests/screenshots
+  # node20-ubuntu:
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #     - uses: actions/checkout@v4
+  #     - uses: actions/setup-node@v3
+  #       with:
+  #         node-version: '20'
+  #     - name: Install project dependencies
+  #       run: |
+  #         echo "Starting npm ci with a 10-minute timeout"
+  #         for i in 1 2 3; do # Retry logic, retry 3 times
+  #           timeout 10m npm ci && break || echo "npm ci failed, retrying ($i/3)..."
+  #         done
+  #     - name: Build packages
+  #       run: npm run build
+  #     - name: Run e2e tests - JS
+  #       run: |
+  #         cd packages/flex-plugin-e2e-tests
+  #         npm run start
+  #       env:
+  #         TS: 0
+  #     - name: Run e2e tests - TS
+  #       env:
+  #         TS: 1
+  #       run: |
+  #         cd packages/flex-plugin-e2e-tests
+  #         npm run start
+  #     - name: Upload Screenshots
+  #       uses: actions/upload-artifact@v3
+  #       if: always()
+  #       with:
+  #         name: Ubuntu-screenshots
+  #         path: packages/flex-plugin-e2e-tests/screenshots
 
   node20-macos:
     runs-on: macos-latest
@@ -139,54 +139,54 @@ jobs:
           name: Macos-screenshots
           path: packages/flex-plugin-e2e-tests/screenshots
 
-  node20-windows:
-    runs-on: windows-latest
-    steps:
-      - uses: actions/checkout@v4
-      - uses: actions/setup-node@v3
-        with:
-          node-version: '20'
-      - name: Install project dependencies
-        run: |
-          echo "Starting npm ci with a 10-minute timeout"
-            $attempts = 3
-            for ($i=1; $i -le $attempts; $i++) {
-              try {
-                $process = Start-Process -FilePath 'npm' -ArgumentList 'ci' -NoNewWindow -PassThru
-                if ($process.WaitForExit(600000)) { # 10 minutes in milliseconds
-                  echo 'npm ci completed successfully'
-                  exit 0
-                } else {
-                  echo 'npm ci timed out. Retrying...'
-                  Stop-Process -Id $process.Id
-                }
-              } catch {
-                echo 'npm ci failed.'
-                if ($i -eq $attempts) {
-                  throw 'npm ci failed after 3 retries.'
-                }
-              }
-            }
-        shell: pwsh
-      - name: Build packages
-        run: npm run build
-      - name: Run e2e tests - JS
-        run: |
-          cd packages/flex-plugin-e2e-tests
-          npm run start
-        env:
-          TS: 0
-      - name: Kill node for Windows os
-        run: taskkill /f /im node.exe
-      - name: Run e2e tests - TS
-        env:
-          TS: 1
-        run: |
-          cd packages/flex-plugin-e2e-tests
-          npm run start
-      - name: Upload Screenshots
-        uses: actions/upload-artifact@v3
-        if: always()
-        with:
-          name: Windows-screenshots
-          path: packages/flex-plugin-e2e-tests/screenshots
+  # node20-windows:
+  #   runs-on: windows-latest
+  #   steps:
+  #     - uses: actions/checkout@v4
+  #     - uses: actions/setup-node@v3
+  #       with:
+  #         node-version: '20'
+  #     - name: Install project dependencies
+  #       run: |
+  #         echo "Starting npm ci with a 10-minute timeout"
+  #           $attempts = 3
+  #           for ($i=1; $i -le $attempts; $i++) {
+  #             try {
+  #               $process = Start-Process -FilePath 'npm' -ArgumentList 'ci' -NoNewWindow -PassThru
+  #               if ($process.WaitForExit(600000)) { # 10 minutes in milliseconds
+  #                 echo 'npm ci completed successfully'
+  #                 exit 0
+  #               } else {
+  #                 echo 'npm ci timed out. Retrying...'
+  #                 Stop-Process -Id $process.Id
+  #               }
+  #             } catch {
+  #               echo 'npm ci failed.'
+  #               if ($i -eq $attempts) {
+  #                 throw 'npm ci failed after 3 retries.'
+  #               }
+  #             }
+  #           }
+  #       shell: pwsh
+  #     - name: Build packages
+  #       run: npm run build
+  #     - name: Run e2e tests - JS
+  #       run: |
+  #         cd packages/flex-plugin-e2e-tests
+  #         npm run start
+  #       env:
+  #         TS: 0
+  #     - name: Kill node for Windows os
+  #       run: taskkill /f /im node.exe
+  #     - name: Run e2e tests - TS
+  #       env:
+  #         TS: 1
+  #       run: |
+  #         cd packages/flex-plugin-e2e-tests
+  #         npm run start
+  #     - name: Upload Screenshots
+  #       uses: actions/upload-artifact@v3
+  #       if: always()
+  #       with:
+  #         name: Windows-screenshots
+  #         path: packages/flex-plugin-e2e-tests/screenshots
