test timeout

diff --git a/.github/workflows/~reusable_e2e.yaml b/.github/workflows/~reusable_e2e.yaml
--- a/.github/workflows/~reusable_e2e.yaml
+++ b/.github/workflows/~reusable_e2e.yaml
@@ -80,7 +80,7 @@ jobs:
         run: |
           echo "Starting npm ci with a 10-minute timeout"
           for i in 1 2 3; do # Retry logic, retry 3 times
-            timeout 20m npm ci && break || echo "npm ci failed, retrying ($i/3)..."
+            timeout 10m npm ci && break || echo "npm ci failed, retrying ($i/3)..."
           done
       - name: Build packages
         run: npm run build
@@ -115,7 +115,7 @@ jobs:
           echo "Starting npm ci with a 10-minute timeout"
           brew install coreutils
           for i in 1 2 3; do # Retry logic, retry 3 times
-            gtimeout 20m npm ci && break || echo "npm ci failed, retrying ($i/3)..."
+            gtimeout 10m npm ci && break || echo "npm ci failed, retrying ($i/3)..."
           done
         shell: bash
       - name: Build packages
@@ -150,7 +150,7 @@ jobs:
         run: |
           echo "Starting npm ci with a 10-minute timeout"
           for i in 1 2 3; do # Retry logic, retry 3 times
-            timeout 20m npm ci && break || echo "npm ci failed, retrying ($i/3)..."
+            timeout 10m npm ci && break || echo "npm ci failed, retrying ($i/3)..."
           done
       - name: Build packages
         run: npm run build
